# THIS FILE IS PART OF HAKONIWA.D
#
# HAKONIWA.D: https://github.com/souk4711/hakoniwa.d
# SPDX-License-Identifier: GPL-3.0-only


# Include a set of built-in configuration
"@include" = [
  "abstractions/os/bare.toml",                    # OS - Bare
  "abstractions/os/freedesktop.toml",             # OS - Freedesktop
  "abstractions/device/dri.toml",                 # Device - DRI
  "abstractions/device/snd.toml",                 # Device - Sound input and output
  "abstractions/socket/dbus-session.toml",        # D-Bus session
  "abstractions/socket/dbus-system.toml",         # D-Bus system
  "abstractions/socket/pipewire.toml",            # Audio Server - PipeWire
  "abstractions/socket/pulseaudio.toml",          # Audio Server - PulseAudio
  "abstractions/socket/wayland.toml",             # Display Server - Wayland
  "abstractions/socket/x11.toml",                 # Display Server - X11
  {% block _include_ %}{% endblock %}             # Customized @include
]

# Persist XDG base directories
{% set _apphome_ = os_env("HOME") + "/.local/share/hakoniwa/apps/" + _appname_ + "/persist" %}
{% for (source, destination) in [
  ( _apphome_ + "/.cache" , os_env("HOME") + "/.cache" ),
  ( _apphome_ + "/.config", os_env("HOME") + "/.config"),
  ( _apphome_ + "/.local" , os_env("HOME") + "/.local" ),
] %}
  {% set _ = fs_mkdir(source) %}
[[mounts]]
source = "{{ source }}"
destination = "{{ destination }}"
rw = true
{% endfor %}

# Customized main contents
{% block _main_ %}{% endblock %}
