# THIS FILE IS PART OF HAKONIWA.D
#
# HAKONIWA.D: https://github.com/souk4711/hakoniwa.d
# SPDX-License-Identifier: GPL-3.0-only


# Include a set of built-in configuration
"@include" = [
  "abstractions/os/bare.toml",                    # OS - Bare
  "abstractions/os/freedesktop.toml",             # OS - Freedesktop
  {% block _include_ %}{% endblock %}             # Customized @include
]

# Persist XDG base directories
{% set _apphome_ = os_env("HOME") + "/.local/share/hakoniwa/apps/" + _appname_ + "/persist" %}
{% for (source, destination) in [
  ( _apphome_ + "/.cache" , os_env("HOME") + "/.cache" ),
  ( _apphome_ + "/.config", os_env("HOME") + "/.config"),
  ( _apphome_ + "/.local" , os_env("HOME") + "/.local" ),
] %}
  {% set _ = fs_mkdir(source) %}
[[mounts]]
source = "{{ source }}"
destination = "{{ destination }}"
rw = true
{% endfor %}

# Customized main contents
{% block _main_ %}{% endblock %}
