# THIS FILE IS PART OF HAKONIWA.D
#
# HAKONIWA.D: https://github.com/souk4711/hakoniwa.d
# SPDX-License-Identifier: GPL-3.0-only


# Include a set of built-in configuration
"@include" = [
  "abstractions/os/bare.toml",                    # OS - Bare
  "abstractions/network/mode/host.toml",          # Network Mode - Host
  "abstractions/network/connect/autoproxy.toml",  # Allow outgoing $ALL_PROXY/... connections
  "abstractions/network/connect/http.toml",       # Allow outgoing HTTP connections
  "abstractions/network/connect/https.toml",      # Allow outgoing HTTPS connections
  {% block _include_ %}{% endblock %}             # Customized @include
]

# Customized main contents
{% block _main_ %}{% endblock %}

# Mount a separate HOME directory
{% set homedir = os_env("HOME") + "/.local/share/hakoniwa/apps/" + _binname_ %}
{% set _ = fs_mkdir(homedir) %}
[[mounts]]
source = "{{ homedir }}"
destination = "{{ os_env("HOME") }}"
rw = true

# COMMAND
{% set binpath = "/usr/bin/" + _binname_ %}
[command]
cmdline = ["{{ binpath }}"]
cwd = "{{ os_env("PWD") }}"
