# THIS FILE IS PART OF HAKONIWA.D
#
# HAKONIWA.D: https://github.com/souk4711/hakoniwa.d
# SPDX-License-Identifier: GPL-3.0-only


# DRI
{% set device = "/dev/dri" %}
{% if path_exists(device) %}
[[mounts]]
source = "{{ device }}"
rw = true
{% endif %}

# NVIDIA
{% for device in find("/dev/nvidia*") %}
[[mounts]]
source = "{{ device }}"
rw = true
{% endfor %}
