# THIS FILE IS PART OF HAKONIWA.D
#
# HAKONIWA.D: https://github.com/souk4711/hakoniwa.d
# SPDX-License-Identifier: GPL-3.0-only


# List of environment variables, described in Freedesktop.org Specifications
{% for name in [
  "XDG_CURRENT_DESKTOP",
  "XDG_MENU_PREFIX",
] %}
  {% if printenv(name) is ne "" %}
[[envs]]
name = "{{ name }}"
  {% endif %}
{% endfor %}

# List of environment variables, described in KDE Frameworks
{% for name in [
  "QT_QPA_PLATFORMTHEME",
  "QT_SCALE_FACTOR",
  "QT_SCREEN_SCALE_FACTORS",
  "QT_AUTO_SCREEN_SCALE_FACTOR",
  "KDE_FULL_SESSION",
  "KDE_SESSION_VERSION",
] %}
  {% if printenv(name) is ne "" %}
[[envs]]
name = "{{ name }}"
  {% endif %}
{% endfor %}

# List of environment variables, described in GNOME Frameworks
{% for name in [
  "GTK_THEME",
  "GTK_USE_PORTAL",
  "GDK_SCALE",
  "GDK_DEBUG",
] %}
  {% if printenv(name) is ne "" %}
[[envs]]
name = "{{ name }}"
  {% endif %}
{% endfor %}
