# THIS FILE IS PART OF HAKONIWA.D
#
# HAKONIWA.D: https://github.com/souk4711/hakoniwa.d
# SPDX-License-Identifier: GPL-3.0-only


# Include a set of DEVKIT configuration
{% include "groups/devkit.toml" %}

# Mount asdf folders
{% set _ = fs_touch(os_env("HOME") + "/.asdfrc") %}
{% set _ = fs_touch(os_env("HOME") + "/.tool-versions") %}
{% for entry in [
  os_env("HOME") + "/.asdf",
  os_env("HOME") + "/.asdfrc",
  os_env("HOME") + "/.tool-versions",
] %}
  {% if path_exists(entry) %}
[[mounts]]
source = "{{ entry }}"
rw = true
  {% endif %}
{% endfor %}

# Mount a separate HOME directory
{% set homedir = os_env("HOME") + "/.local/share/hakoniwa/apps/asdf" %}
{% set _ = fs_mkdir(homedir) %}
[[mounts]]
source = "{{ homedir }}"
destination = "{{ HOME }}"
rw = true

# COMMAND
[command]
cmdline = ["/usr/bin/asdf"]
cwd = "{{ PWD }}"

# Embed user profile
{% include "local/asdf.toml" ignore missing %}
