# THIS FILE IS PART OF HAKONIWA.D
#
# HAKONIWA.D: https://github.com/souk4711/hakoniwa.d
# SPDX-License-Identifier: GPL-3.0-only


# Constants
{% set _pkgname_ = "google-chrome" %}
{% set _binname_ = "google-chrome-stable" %}

# Use preset desktop-network
{% extends "presets/desktop-network.toml" %}
{% block _include_ %}
  "abstractions/device/v4l.toml",                 # Device - Video capture
  "abstractions/filesystem/xdg-download.toml",    # Share Folder - $HOME/Downloads
{% endblock %}

# Customized user profile
{% include ("local/" + _pkgname_ + ".toml") ignore missing %}
