# THIS FILE IS PART OF HAKONIWA.D
#
# HAKONIWA.D: https://github.com/souk4711/hakoniwa.d
# SPDX-License-Identifier: GPL-3.0-only


# Constants
{% set _pkgname_ = "ktorrent" %}
{% set _binname_ = "ktorrent" %}

# Include a preset configuration of BitTorrent
{% include "presets/bittorrent.toml" %}

# Customized user profile
{% include ("local/" + _pkgname_ + ".toml") ignore missing %}
