# THIS FILE IS PART OF HAKONIWA.D
#
# HAKONIWA.D: https://github.com/souk4711/hakoniwa.d
# SPDX-License-Identifier: GPL-3.0-only


# Constants
{% set _pkgname_ = "makepkg" %}
{% set _binname_ = "makepkg" %}

# Use preset terminal-network
{% extends "presets/terminal-network.toml" %}
{% block _include_ %}
  "abstractions/filesystem/xdg-code.toml",        # Share Folder - $HOME/Code
{% endblock %}

# Mount /var/lib which stores application's data
[[mounts]]
source = "/var/lib/pacman"

# Mount AUR folders
{% for entry in [
  os_env("HOME") + "/.cache/paru",
  os_env("HOME") + "/.cache/yay",
] %}
  {% if path_exists(entry) %}
[[mounts]]
source = "{{ entry }}"
rw = true
  {% endif %}
{% endfor %}

# Donot try chown in fakeroot environment
[[envs]]
name = "FAKEROOTDONTTRYCHOWN"
value = "1"

# Donot impose FS restrictions on /home
{% for entry in [
  "/home",
  "/tmp",
] %}
[[landlock.fs]]
path = "{{ entry }}"
access = "rwx"
{% endfor %}

# Customized user profile
{% include ("local/" + _pkgname_ + ".toml") ignore missing %}
