# THIS FILE IS PART OF HAKONIWA.D
#
# HAKONIWA.D: https://github.com/souk4711/hakoniwa.d
# SPDX-License-Identifier: GPL-3.0-only


# Include a set of built-in configuration
"@include" = [
  "abstractions/os/linux.toml",                   # Base
  "abstractions/network/mode/host.toml",          # Network Mode - Host
  "abstractions/network/connect/autoproxy.toml",  # Allow outgoing $ALL_PROXY/... connections
  "abstractions/network/connect/http.toml",       # Allow outgoing HTTP connections
  "abstractions/network/connect/https.toml",      # Allow outgoing HTTPS connections
  "abstractions/filesystem/xdg-code.toml",        # Share Folder - $HOME/Code
]

# Mount /var/lib which stores application's data
[[mounts]]
source = "/var/lib/pacman"

# Mount AUR folders
{% for entry in [
  os_env("HOME") + "/.cache/paru",
  os_env("HOME") + "/.cache/yay",
] %}
  {% if path_exists(entry) %}
[[mounts]]
source = "{{ entry }}"
rw = true
  {% endif %}
{% endfor %}

# Donot try chown in fakeroot environment
[[envs]]
name = "FAKEROOTDONTTRYCHOWN"
value = "1"

# Donot impose FS restrictions
[[landlock.resources]]
type = "fs"
unrestrict = true

# Mount a separate HOME directory
{% set homedir = os_env("HOME") + "/.local/share/hakoniwa/apps/makepkg" %}
{% set _ = fs_mkdir(homedir) %}
[[mounts]]
source = "{{ homedir }}"
destination = "{{ HOME }}"
rw = true

# COMMAND
[command]
cmdline = ["/usr/bin/makepkg"]
cwd = "{{ PWD }}"

# Embed user profile
{% include "local/makepkg.toml" ignore missing %}
