# THIS FILE IS PART OF HAKONIWA.D
#
# HAKONIWA.D: https://github.com/souk4711/hakoniwa.d
# SPDX-License-Identifier: GPL-3.0-only


# Constants
{% set _pkgname_ = "mise" %}
{% set _binname_ = "mise" %}

# Use preset terminal-network
{% extends "presets/terminal-network.toml" %}
{% block _include_ %}
  "abstractions/filesystem/xdg-code.toml",        # Share Folder - $HOME/Code
{% endblock %}

# Mount mise folders
{% set _ = fs_mkdir(os_env("HOME") + "/.cache/mise")        %}
{% set _ = fs_mkdir(os_env("HOME") + "/.config/mise")       %}
{% set _ = fs_mkdir(os_env("HOME") + "/.local/share/mise")  %}
{% set _ = fs_mkdir(os_env("HOME") + "/.local/state/mise")  %}
{% set _ = fs_touch(os_env("HOME") + "/.tool-versions")     %}
{% for entry in [
  os_env("HOME") + "/.cache/mise",
  os_env("HOME") + "/.config/mise",
  os_env("HOME") + "/.local/share/mise",
  os_env("HOME") + "/.local/state/mise",
  os_env("HOME") + "/.tool-versions",
] %}
  {% if path_exists(entry) %}
[[mounts]]
source = "{{ entry }}"
rw = true
  {% endif %}
{% endfor %}

# Donot impose FS restrictions on /tmp
[[landlock.fs]]
path = "/tmp"
access = "rwx"

# Donot impose FS restrictions on /home
[[landlock.fs]]
path = "/home"
access = "rwx"

# Customized user profile
{% include ("local/" + _pkgname_ + ".toml") ignore missing %}
