# THIS FILE IS PART OF HAKONIWA.D
#
# HAKONIWA.D: https://github.com/souk4711/hakoniwa.d
# SPDX-License-Identifier: GPL-3.0-only


# Constants
{% set _pkgname_ = "obsidian" %}
{% set _binname_ = "obsidian" %}

# Use preset desktop-network
{% extends "presets/desktop-network.toml" %}
{% block _include_ %}
  "abstractions/filesystem/trash.toml",           # Share Folder - $HOME/.local/share/Trash
  "abstractions/filesystem/xdg-notes.toml",       # Share Folder - $HOME/Downloads
{% endblock %}

# Customized user profile
{% include ("local/" + _pkgname_ + ".toml") ignore missing %}
