# THIS FILE IS PART OF HAKONIWA.D
#
# HAKONIWA.D: https://github.com/souk4711/hakoniwa.d
# SPDX-License-Identifier: GPL-3.0-only


# Include a set of BROWSER configuration
{% include "groups/browser.toml" %}

# Mount a separate HOME directory
{% set homedir = os_env("HOME") + "/.local/share/hakoniwa/apps/vivaldi" %}
{% set _ = fs_mkdir(homedir) %}
[[mounts]]
source = "{{ homedir }}"
destination = "{{ HOME }}"
rw = true

# COMMAND
[command]
cmdline = ["/usr/bin/vivaldi"]
cwd = "{{ HOME }}"

# Embed user profile
{% include "local/vivaldi.toml" ignore missing %}
