# THIS FILE IS PART OF HAKONIWA.D
#
# HAKONIWA.D: https://github.com/souk4711/hakoniwa.d
# SPDX-License-Identifier: GPL-3.0-only


# Constants
{% set _pkgname_ = "zen-browser" %}
{% set _binname_ = "zen" %}

# Extend preset BROWSER
{% extends "presets/browser.toml" %}

# Customized user profile
{% include ("local/" + _pkgname_ + ".toml") ignore missing %}
