# THIS FILE IS PART OF HAKONIWA.D
#
# HAKONIWA.D: https://github.com/souk4711/hakoniwa.d
# SPDX-License-Identifier: GPL-3.0-only


# Jellyfin is the volunteer-built media solution that puts you in control of your media
[[landlock.net]]
port = 8096
access = "tcp.connect"
