# THIS FILE IS PART OF HAKONIWA.D
#
# HAKONIWA.D: https://github.com/souk4711/hakoniwa.d
# SPDX-License-Identifier: GPL-3.0-only


# HTTPS is a modified HTTP used to serve Web pages when security is important
[[landlock.net]]
port = 443
access = "tcp.connect"
