# THIS FILE IS PART OF HAKONIWA.D
#
# HAKONIWA.D: https://github.com/souk4711/hakoniwa.d
# SPDX-License-Identifier: GPL-3.0-only


# Mount unhidden folders
{% for entry in fs_glob(os_env("HOME") + "/[!.]*") %}
  {% if path_is_dir(entry) %}
[[mounts]]
source = "{{ entry }}"
  {% endif %}
{% endfor %}
