# THIS FILE IS PART OF HAKONIWA.D
#
# HAKONIWA.D: https://github.com/souk4711/hakoniwa.d
# SPDX-License-Identifier: GPL-3.0-only


# Use the host's network
[network]
mode = "host"

# Setting DNS servers
{% if path_is_symlink("/etc/resolv.conf") %}
{% set original = readlink("/etc/resolv.conf") %}
  {% if original is endingwith "/run/systemd/resolve/stub-resolv.conf" %}
[[mounts]]
source = "/run/systemd/resolve"
  {% endif %}
{% endif %}
