# THIS FILE IS PART OF HAKONIWA.D
#
# HAKONIWA.D: https://github.com/souk4711/hakoniwa.d
# SPDX-License-Identifier: GPL-3.0-only


# Include a set of built-in configuration
"@include" = [
  "abstractions/os/linux.toml",                   # OS
  "abstractions/device/dri.toml",                 # Device - DRI
  "abstractions/device/snd.toml",                 # Device - Sound input and output
  "abstractions/socket/dbus-session.toml",        # D-Bus session
  "abstractions/socket/dbus-system.toml",         # D-Bus system
  "abstractions/socket/pipewire.toml",            # Audio Server - PipeWire
  "abstractions/socket/pulseaudio.toml",          # Audio Server - PulseAudio
  "abstractions/socket/wayland.toml",             # Display Server - Wayland
  "abstractions/socket/x11.toml",                 # Display Server - X11
  "abstractions/network/mode/pasta.toml",         # Network Mode - Pasta
  "abstractions/network/connect/autoproxy.toml",  # Allow outgoing $ALL_PROXY/... connections
  "abstractions/network/connect/http.toml",       # Allow outgoing HTTP connections
  "abstractions/network/connect/https.toml",      # Allow outgoing HTTPS connections
  {% block _include_ %}{% endblock %}             # Customized @include
]

# Customized main contents
{% block _main_ %}{% endblock %}

# Mount a separate HOME directory
{% set homedir = os_env("HOME") + "/.local/share/hakoniwa/apps/" + _binname_ %}
{% set _ = fs_mkdir(homedir) %}
[[mounts]]
source = "{{ homedir }}"
destination = "{{ HOME }}"
rw = true

# COMMAND
{% set binpath = "/usr/bin/" + _binname_ %}
[command]
cmdline = ["{{ binpath }}"]
cwd = "{{ HOME }}"
