# THIS FILE IS PART OF HAKONIWA.DAdd commentMore actions
#
# HAKONIWA.D: https://github.com/souk4711/hakoniwa.d
# SPDX-License-Identifier: GPL-3.0-only


# Constants
{% set _appname_ = "arianna" %}

# Include a preset configuration
{% include "presets/desktop-standalone/document-viewer.toml" %}
{% include "abstractions/network/mode/host.toml" %}

# https://github.com/KDE/arianna/blob/559a94b43a6e778cd45cdc8165fcfc1caf0414c2/src/bookserver.cpp#L40
[[landlock.net]]
port = 45961
access = "tcp.bind"

# https://github.com/KDE/arianna/blob/559a94b43a6e778cd45cdc8165fcfc1caf0414c2/src/content/ui/EpubViewerPage.qml#L55
[[landlock.net]]
port = 45961
access = "tcp.connect"

# Customized user profile
{% include ("local/" + _appname_ + ".toml") ignore missing %}
