# THIS FILE IS PART OF HAKONIWA.D
#
# HAKONIWA.D: https://github.com/souk4711/hakoniwa.d
# SPDX-License-Identifier: GPL-3.0-only


# Constants
{% set _appname_ = "asdf" %}

# Include a preset configuration
{% include "presets/devkit.toml" %}

# Mount ASDF_DATA_DIR
{% if os_env("ASDF_DATA_DIR") is eq "" %}
  {% set asdf_data_dir = os_env("HOME") + "/.asdf" %}
{% else %}
  {% set asdf_data_dir = os_env("ASDF_DATA_DIR")   %}
{% endif %}
{% set _ = fs_mkdir(asdf_data_dir) %}
[[mounts]]
source = "{{ asdf_data_dir }}"
rw = true

# Mount ASDF_CONFIG_FILE
{% if os_env("ASDF_CONFIG_FILE") is eq "" %}
  {% set asdf_config_file = os_env("HOME") + "/.asdfrc" %}
{% else %}
  {% set asdf_config_file = os_env("ASDF_CONFIG_FILE")   %}
{% endif %}
{% set _ = fs_touch(asdf_config_file) %}
[[mounts]]
source = "{{ asdf_config_file }}"
rw = true

# Mount .tool-versions
{% set tool_versions = os_env("HOME") + "/.tool-versions" %}
{% set _ = fs_touch(tool_versions) %}
[[mounts]]
source = "{{ tool_versions }}"
rw = true

# List of environment variables exported to the application
{% for name in [
  "ASDF_DATA_DIR",
  "ASDF_CONFIG_FILE",
  "ASDF_CONCURRENCY",
] %}
  {% if os_env(name) is ne "" %}
[[envs]]
name = "{{ name }}"
  {% endif %}
{% endfor %}

# Customized user profile
{% include ("local/" + _appname_ + ".toml") ignore missing %}
