# THIS FILE IS PART OF HAKONIWA.D
#
# HAKONIWA.D: https://github.com/souk4711/hakoniwa.d
# SPDX-License-Identifier: GPL-3.0-only


# Constants
{% set _appname_ = "floorp" %}

# Include a preset configuration
{% include "presets/browser.toml" %}

# Persist HOME subdirs
{% set source = _apphome_ + "/.floorp" %}
{% set destination = os_env("HOME") + "/.floorp" %}
{% set _ = fs_mkdir(source) %}
[[mounts]]
source = "{{ source }}"
destination = "{{ destination }}"
rw = true

# Customized user profile
{% include ("local/" + _appname_ + ".toml") ignore missing %}
