# THIS FILE IS PART OF HAKONIWA.D
#
# HAKONIWA.D: https://github.com/souk4711/hakoniwa.d
# SPDX-License-Identifier: GPL-3.0-only


# Constants
{% set _appname_ = "gpodder" %}

# Include a preset configuration
{% include "presets/podcast-client.toml" %}
{% include "abstractions/socket/at-spi.toml" %}

# Customized user profile
{% include ("local/" + _appname_ + ".toml") ignore missing %}
