# THIS FILE IS PART OF HAKONIWA.D
#
# HAKONIWA.D: https://github.com/souk4711/hakoniwa.d
# SPDX-License-Identifier: GPL-3.0-only


# Constants
{% set _appname_ = "librewolf" %}

# Include a preset configuration
{% include "presets/desktop-web/browser.toml" %}

# Persist HOME subdirs
{% set source = _apphome_ + "/.librewolf" %}
{% set destination = printenv("HOME") + "/.librewolf" %}
{% set _ = mkdir_p(source) %}
[[mounts]]
source = "{{ source }}"
destination = "{{ destination }}"
rw = true

# Customized user profile
{% include ("local/" + _appname_ + ".toml") ignore missing %}
