# THIS FILE IS PART OF HAKONIWA.D
#
# HAKONIWA.D: https://github.com/souk4711/hakoniwa.d
# SPDX-License-Identifier: GPL-3.0-only


# Constants
{% set _appname_ = "loupe" %}

# Include a preset configuration
{% include "presets/image-viewer.toml" %}
{% include "abstractions/socket/at-spi.toml" %}

# Donot impose Filesystem restrictions, required by Gio
[[landlock.resources]]
type = "fs"
unrestrict = true

# Customized user profile
{% include ("local/" + _appname_ + ".toml") ignore missing %}
