# THIS FILE IS PART OF HAKONIWA.D
#
# HAKONIWA.D: https://github.com/souk4711/hakoniwa.d
# SPDX-License-Identifier: GPL-3.0-only


# Constants
{% set _appname_ = "mise" %}

# Include a preset configuration
{% include "presets/devkit.toml" %}

# Mount mise folders
{% set _ = mkdir_p(printenv("HOME") + "/.cache/mise")        %}
{% set _ = mkdir_p(printenv("HOME") + "/.config/mise")       %}
{% set _ = mkdir_p(printenv("HOME") + "/.local/share/mise")  %}
{% set _ = mkdir_p(printenv("HOME") + "/.local/state/mise")  %}
{% set _ = touch(printenv("HOME") + "/.tool-versions")     %}
{% for entry in [
  printenv("HOME") + "/.cache/mise",
  printenv("HOME") + "/.config/mise",
  printenv("HOME") + "/.local/share/mise",
  printenv("HOME") + "/.local/state/mise",
  printenv("HOME") + "/.tool-versions",
] %}
  {% if path_exists(entry) %}
[[mounts]]
source = "{{ entry }}"
rw = true
  {% endif %}
{% endfor %}

# Customized user profile
{% include ("local/" + _appname_ + ".toml") ignore missing %}
