# THIS FILE IS PART OF HAKONIWA.D
#
# HAKONIWA.D: https://github.com/souk4711/hakoniwa.d
# SPDX-License-Identifier: GPL-3.0-only


# Constants
{% set _appname_ = "mpv" %}

# Include a preset configuration
{% include "presets/desktop-standalone/video-player.toml" %}

# Donot impose Filesystem restrictions, required by mp.command_native (thumbfast.lua -> mp.command_native)
[[landlock.resources]]
type = "fs"
unrestrict = true

# Customized user profile
{% include ("local/" + _appname_ + ".toml") ignore missing %}
