# THIS FILE IS PART OF HAKONIWA.D
#
# HAKONIWA.D: https://github.com/souk4711/hakoniwa.d
# SPDX-License-Identifier: GPL-3.0-only


# Constants
{% set _binname_ = "qutebrowser" %}

# Include a preset configuration
{% include "presets/browser.toml" %}

# Customized user profile
{% include ("local/" + _binname_ + ".toml") ignore missing %}
