# THIS FILE IS PART OF HAKONIWA.D
#
# HAKONIWA.D: https://github.com/souk4711/hakoniwa.d
# SPDX-License-Identifier: GPL-3.0-only


# Constants
{% set _appname_ = "totem" %}

# Include a preset configuration
{% include "presets/video-player.toml" %}

# Customized user profile
{% include ("local/" + _appname_ + ".toml") ignore missing %}
