# THIS FILE IS PART OF HAKONIWA.D
#
# HAKONIWA.D: https://github.com/souk4711/hakoniwa.d
# SPDX-License-Identifier: GPL-3.0-only


# Constants
{% set _binname_ = "wechat" %}

# Include a preset configuration
{% include "presets/messager.toml" %}

# Enables automatic scaling, based on the monitor's pixel density
[[envs]]
name = "QT_AUTO_SCREEN_SCALE_FACTOR"
value = "1"

# Customized user profile
{% include ("local/" + _binname_ + ".toml") ignore missing %}
