# THIS FILE IS PART OF HAKONIWA.D
#
# HAKONIWA.D: https://github.com/souk4711/hakoniwa.d
# SPDX-License-Identifier: GPL-3.0-only


# Constants
{% set _appname_ = "zen" %}

# Include a preset configuration
{% include "presets/desktop-web/browser.toml" %}

# Persist HOME subdirs
{% for (source, destination) in [
  ( _apphome_ + "/.mozilla", os_env("HOME") + "/.mozilla"),
  ( _apphome_ + "/.zen", os_env("HOME") + "/.zen"),
] %}
  {% set _ = fs_mkdir(source) %}
[[mounts]]
source = "{{ source }}"
destination = "{{ destination }}"
rw = true
{% endfor %}

# Customized user profile
{% include ("local/" + _appname_ + ".toml") ignore missing %}
