# THIS FILE IS PART OF HAKONIWA.D
#
# HAKONIWA.D: https://github.com/souk4711/hakoniwa.d
# SPDX-License-Identifier: GPL-3.0-only


# Extend preset DESKTOP-NETWORK
{% extends "presets/core/desktop-network.toml" %}
{% block _include_ %}
  "abstractions/socket/dbus-session.toml",        # D-Bus session
  "abstractions/socket/dbus-system.toml",         # D-Bus system
  "abstractions/filesystem/xdg-download.toml",    # Share Folder - $HOME/Downloads
{% endblock %}
