# THIS FILE IS PART OF HAKONIWA.D
#
# HAKONIWA.D: https://github.com/souk4711/hakoniwa.d
# SPDX-License-Identifier: GPL-3.0-only


# Include a set of built-in configuration
"@include" = [
  "abstractions/os/linux.toml",                   # OS
  {% block include %}{% endblock %}
]

# Mount a separate HOME directory
{% set homedir = os_env("HOME") + "/.local/share/hakoniwa/apps/" + _pkgname_ %}
{% set _ = fs_mkdir(homedir) %}
[[mounts]]
source = "{{ homedir }}"
destination = "{{ HOME }}"
rw = true

# COMMAND
{% set binpath = "/usr/bin/" + _binname_ %}
[command]
cmdline = ["{{ binpath }}"]
cwd = "{{ HOME }}"
