# THIS FILE IS PART OF HAKONIWA.D
#
# HAKONIWA.D: https://github.com/souk4711/hakoniwa.d
# SPDX-License-Identifier: GPL-3.0-only


# Create a user-mode networking stack using pasta
[network]
mode = "pasta"
options = ["-T", "auto", "-t", "auto"]
