# THIS FILE IS PART OF HAKONIWA.D
#
# HAKONIWA.D: https://github.com/souk4711/hakoniwa.d
# SPDX-License-Identifier: GPL-3.0-only


# Include a set of built-in configuration
"@include" = [
  "abstractions/os/linux.toml",                   # Base
  "abstractions/network/mode/pasta.toml",         # Network Mode - Pasta
  "abstractions/network/connect/autoproxy.toml",  # Allow outgoing $ALL_PROXY/... connections
  "abstractions/network/connect/http.toml",       # Allow outgoing HTTP connections
  "abstractions/network/connect/https.toml",      # Allow outgoing HTTPS connections
]

# Mount /var/lib which stores application's data
[[mounts]]
source = "/var/lib/pacman"

# Mount $PWD
[[mounts]]
source = "{{ PWD }}"
destination = "/tmp/makepkg"
rw = true

# Allow READ-WRITE-EXEC on $PWD
[[landlock.fs]]
path = "/tmp/makepkg"
access = "rwx"

# Mount a separate HOME directory
{% set homedir = os_env("HOME") + "/.local/share/hakoniwa/apps/makepkg" %}
{% set _ = fs_mkdir(homedir) %}
[[mounts]]
source = "{{ homedir }}"
destination = "{{ HOME }}"
rw = true

# COMMAND
[command]
cmdline = ["/usr/bin/makepkg"]
cwd = "/tmp/makepkg"

# Embed user profile
{% include "local/makepkg.toml" ignore missing %}
