# THIS FILE IS PART OF HAKONIWA.D
#
# HAKONIWA.D: https://github.com/souk4711/hakoniwa.d
# SPDX-License-Identifier: GPL-3.0-only


# Use preset TERMINAL-NETWORK as base skeleton
{% extends "presets/core/terminal-network.toml" %}

# Customized @include
{% block _include_ %}
  "abstractions/network/bind/any.toml",               # Allow incoming connections
  "abstractions/filesystem/xdg-code.toml",            # Share Folder - $HOME/Code
  "abstractions/filesystem/xdg-downloads.toml",       # Share Folder - $HOME/Downloads
{% endblock %}

# Customized main contents
{% block _main_ %}
[[landlock.resources]]
type = "fs"
unrestrict = true

[command]
cmdline = ["{{ "/usr/bin/" + _appname_ }}"]
cwd = "{{ os_env("PWD") }}"
{% endblock %}
