# THIS FILE IS PART OF HAKONIWA.D
#
# HAKONIWA.D: https://github.com/souk4711/hakoniwa.d
# SPDX-License-Identifier: GPL-3.0-only


# D-Bus socket
{% set address = printenv("DBUS_SESSION_BUS_ADDRESS") %}
{% if address is eq "" %}
  {% set socket = printenv("XDG_RUNTIME_DIR") + "/bus" %}
  {% if path_exists(socket) %}
[[mounts]]
source = "{{ socket }}"
rw = true
  {% endif %}
{% elif address is startingwith "unix:path=" %}
  {% set socket = address | replace("unix:path=", "") %}
  {% if path_exists(socket) %}
[[mounts]]
source = "{{ socket }}"
rw = true
  {% endif %}
{% endif %}

# List of environment variables exported to the application
{% for name in [
  "DBUS_SESSION_BUS_ADDRESS",
] %}
  {% if printenv(name) is ne "" %}
[[envs]]
name = "{{ name }}"
  {% endif %}
{% endfor %}
