# THIS FILE IS PART OF HAKONIWA.D
#
# HAKONIWA.D: https://github.com/souk4711/hakoniwa.d
# SPDX-License-Identifier: GPL-3.0-only


# PipeWire socket
{% set socket = printenv("XDG_RUNTIME_DIR") + "/pipewire-0" %}
{% if path_exists(socket) %}
[[mounts]]
source = "{{ socket }}"
rw = true
{% endif %}
