# THIS FILE IS PART OF HAKONIWA.D
#
# HAKONIWA.D: https://github.com/souk4711/hakoniwa.d
# SPDX-License-Identifier: GPL-3.0-only


# PulseAudio socket
{% set socket = os_env("XDG_RUNTIME_DIR") + "/pulse" %}
{% if path_exists(socket) %}
[[mounts]]
source = "{{ socket }}"
rw = true
{% endif %}

# PulseAudio cookie
{% set cookie = os_env("HOME") + "/.config/pulse" %}
{% if path_exists(cookie) %}
[[mounts]]
source = "{{ cookie }}"
rw = true
{% endif %}
