# THIS FILE IS PART OF HAKONIWA.D
#
# HAKONIWA.D: https://github.com/souk4711/hakoniwa.d
# SPDX-License-Identifier: GPL-3.0-only


{% set wayland_display = os_env("WAYLAND_DISPLAY")%}
{% if wayland_display is ne "" %}
  # Wayland socket
  {% set socket = os_env("XDG_RUNTIME_DIR") + "/" +  wayland_display %}
  {% if path_exists(socket) %}
[[mounts]]
source = "{{ socket }}"
rw = true
  {% endif %}

  # List of environment variables exported to the application
  {% for name in [
    "WAYLAND_DISPLAY",
  ] %}
    {% if os_env(name) is ne "" %}
[[envs]]
name = "{{ name }}"
    {% endif %}
  {% endfor %}
{% endif %}
