# THIS FILE IS PART OF HAKONIWA.D
#
# HAKONIWA.D: https://github.com/souk4711/hakoniwa.d
# SPDX-License-Identifier: GPL-3.0-only


{% set display = os_env("DISPLAY")%}
{% if display is ne "" %}
  # X socket
  {% set socket = "/tmp/.X11-unix" %}
  {% if path_exists(socket) %}
[[mounts]]
source = "{{ socket }}"
rw = true
  {% endif %}

  # X authority file
  {% set xauthority = os_env("XAUTHORITY") %}
  {% if path_exists(xauthority) %}
[[mounts]]
source = "{{ xauthority }}"
rw = true
  {% endif %}

  # List of environment variables exported to the application
  {% for name in [
    "DISPLAY",
    "XAUTHORITY",
  ] %}
    {% if os_env(name) is ne "" %}
[[envs]]
name = "{{ name }}"
    {% endif %}
  {% endfor %}

  # Required by MIT Shared Memory Extension
[[namespaces]]
type = "ipc"
share = true
{% endif %}
