name: Continuous integration

on: [push, pull_request]

jobs:
  lints:
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Run lint
        run: make lint

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install libseccomp
        run: |
          sudo apt-get update
          sudo apt install libseccomp-dev
      - name: Install hakoniwa
        run: |
          sudo make install_hakoniwa
      - name: Run test
        run: make test
