name: Continuous integration

on: [push, pull_request]

jobs:
  lints:
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Run ShellCheck
        run: make lints
