name: Continuous integration

on: [push, pull_request]

jobs:
  lints:
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Run lint
        run: make lint

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Install hakoniwa
        run: |
          sudo env PATH="$PATH" rustup default stable
          sudo env PATH="$PATH" make install_hakoniwa
      - name: Setup Bats and bats libs
        id: setup-bats
        uses: bats-core/bats-action@3.0.0
      - name: Run test
        run: |
          mkdir -p ~/Code
          make test
